# Generated by Django 2.2.2 on 2019-06-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='loyalty',
            field=models.IntegerField(choices=[(0, 'gold'), (1, 'star'), (2, 'platinum')], default=0),
        ),
    ]
